name: Run Tasks

on:
  schedule:
    - cron: "0 */24 * * *"
  push:
    branches: [ master ]
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Explanation'     
        required: true
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - name: Build
      run: yarn build
    - name: Run Tasks
      env:
        NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        HARVARD_ART_API_KEY: ${{ secrets.HARVARD_ART_API_KEY }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: yarn start
