name: Run Tasks

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: [ master ]
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Explanation'     
        required: true
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - name: Run Tasks
      env:
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: yarn start
    - name: Update resources
      uses: test-room-7/action-update-file@v1
      with:
        file-path: README.md
        commit-msg: ":construction_worker: github action update"
        github-token: ${{ secrets.GITHUB_TOKEN }}
